name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          target/
        key: cargo-${{ runner.os }}-${{ hashFiles( '**/Cargo.lock' ) }}
        restore-keys: |
          cargo-${{ runner.os }}-
    - name: Build
      run: cargo build --release --locked --verbose
    - name: Lint
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
